name: Honeycomb Buildevents
author: Honeycomb
description: Trace GitHub Action workflows with Honeycomb

branding:
  icon: activity
  color: yellow

inputs:
  apikey:
    description: A Honeycomb API key - needed to send traces.
    required: true
  dataset:
    description: The Honeycomb dataset to send traces to.
    required: true
  job-status:
    description: The job status.
    required: true
  matrix-key:
    description: Set this to a key unique for this matrix cell, only useful when using a build matrix.
    required: false

outputs:
  trace-id:
    description: Trace id set by the Action. Useful for workflows with multiple jobs.
  start-timestamp:
    description: Timestamp set by the Action. Useful for workflows with multiple jobs.

runs:
  using: node12
  main: dist/index.js
  post: dist/index.js
