name: Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 * * * *" # run once every hour

jobs:
  start-trace:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set trace-start
        id: set-trace-start
        run: |
          echo ::set-output name=trace-start::$(date +%s)
      - uses: ./
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: gha-buildevents_integration

    outputs:
      trace-start: ${{ steps.set-trace-start.outputs.trace-start }}

  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    needs: [ start-trace ]

    steps:
      - uses: actions/checkout@v2

      - name: Buildevents
        uses: ./
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: gha-buildevents_integration
          trace-start: ${{ needs.start-trace.outputs.trace-start}}

      - name: Print contents of BUILDEVENT_FILE
        run: |
          echo Contents of BUILDEVENT_FILE:
          cat $BUILDEVENT_FILE

      - run: |
          echo "STEP_ID=0" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: |
          buildevents cmd $TRACE_ID $STEP_ID sleep -- sleep 5
      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'step 1'

      - run: |
          echo "STEP_ID=1" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: |
          buildevents cmd $TRACE_ID $STEP_ID 'sleep some more' -- sleep 2
      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'step 2'

  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    needs: [ start-trace ]

    strategy:
      fail-fast: false
      matrix:
        value: [ valueA, valueB ]

    steps:
      - uses: actions/checkout@v2

      - name: Buildevents
        uses: ./
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: gha-buildevents_integration
          matrix-key: ${{ matrix.value }}
          trace-start: ${{ needs.start-trace.outputs.trace-start}}

      - run: |
          echo "STEP_ID=0" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: |
          buildevents cmd $TRACE_ID $STEP_ID ${{ matrix.value }} -- echo The matrix value is ${{ matrix.value }}
      - run: |
          buildevents cmd $TRACE_ID $STEP_ID sleep -- sleep 2
      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'step 1'

  end-trace:
    runs-on: ubuntu-latest
    needs: [ start-trace, smoke-test, matrix ]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2

      - uses: technote-space/workflow-conclusion-action@v3

      - uses: ./
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: gha-buildevents_integration
          trace-start: ${{ needs.start-trace.outputs.trace-start}}
          status: ${{ env.WORKFLOW_CONCLUSION }}
